### ISSUE TITLE
zef install fails due to test failure in t/07_chunkedrequestecho.t

### ISSUE THREAD

**Issue by evanmiller** [perl6/perl6-http-server-async#32]
```
$ perl6 --version
This is Rakudo version 2017.07-60-g2fb8c7258 built on MoarVM version 2017.07-15-g0729f841
implementing Perl 6.c.
```

```
$  zef install HTTP::Server::Async
===> Searching for: HTTP::Server::Async
===> Searching for missing dependencies: HTTP::Server
===> Testing: HTTP::Server:ver('0.1.1'):auth('github:tony-o')
===> Testing [OK] for HTTP::Server:ver('0.1.1'):auth('github:tony-o')
===> Testing: HTTP::Server::Async:ver('0.1.7'):auth('github:tony-o')
Could not receive data from socket: Connection reset by peer
  in block <unit> at t/07_chunkedrequestecho.t line 29


===> Testing [FAIL]: HTTP::Server::Async:ver('0.1.7'):auth('github:tony-o')
Aborting due to test failure: HTTP::Server::Async:ver('0.1.7'):auth('github:tony-o') (use --force-test to override)
  in code  at /Users/emiller/Code/rakudo/install/share/perl6/site/sources/3393EDA469A9E8925A633FF7A533AB41141495DA (Zef::Client) line 373
  in method test at /Users/emiller/Code/rakudo/install/share/perl6/site/sources/3393EDA469A9E8925A633FF7A533AB41141495DA (Zef::Client) line 351
  in code  at /Users/emiller/Code/rakudo/install/share/perl6/site/sources/3393EDA469A9E8925A633FF7A533AB41141495DA (Zef::Client) line 528
  in sub  at /Users/emiller/Code/rakudo/install/share/perl6/site/sources/3393EDA469A9E8925A633FF7A533AB41141495DA (Zef::Client) line 525
  in method install at /Users/emiller/Code/rakudo/install/share/perl6/site/sources/3393EDA469A9E8925A633FF7A533AB41141495DA (Zef::Client) line 631
  in sub MAIN at /Users/emiller/Code/rakudo/install/share/perl6/site/sources/ED3033E8712BCF9F6DE53678B14A54705DF211A6 (Zef::CLI) line 152
  in block <unit> at /Users/emiller/Code/rakudo/install/share/perl6/site/resources/6182CA1C8C9C6ED5BBB3076B522103070B37DDA4 line 1
  in sub MAIN at /Users/emiller/Code/rakudo/install/share/perl6/site/bin/zef line 2
  in block <unit> at /Users/emiller/Code/rakudo/install/share/perl6/site/bin/zef line 2
```

Any ideas?

**Comment by tony-o** [comment]
@evanmiller  - I believe this is a problem that is resolved in perl`6.d`.  Are you able to upgrade to that (it's called moar-nom in rakudobrew)?  Barring that, a `--force-install` should install and get you working for most things until `6.d` is fully released.

**Comment by evanmiller** [comment]
@tony-o -- I'm using the `nom` branch of Rakudo. Should I point it to a particular branch of MoarVM?

**Comment by tony-o** [comment]
Are you using rakudobrew or are you building directly from the rakudo repository?

**Comment by evanmiller** [comment]
I am building directly from the GitHub repo.

**Comment by tony-o** [comment]
The issue *was* in the backend of MoarVM and being able to read/write to socket handles cross channel/supply.  The issue, as far as we've been able to tell, should be resolved.  Can you build the latest Moar and provide the output of just that test file?  `perl6 -Ilib --ll-exception t/07_chunkedrequestecho.t`

**Comment by evanmiller** [comment]
I am still seeing the same error. I don't know how MoarVM versioning works, but I believe I am building the latest MoarVM (note version difference from the first report):

```
perl6 --version
This is Rakudo version 2017.07-60-g2fb8c7258 built on MoarVM version 2017.07-230-gd6d7d5eb
implementing Perl 6.c.
```

I would be curious to see the version info on systems where the test passes.

**Comment by tony-o** [comment]
Here it is from my debian machine.  Tests are also passing on OSX for me.  What OS are you on?  May have to build a vm.. 

```tonyo@enoch:~$ perl6 -v
This is Rakudo version 2017.07-71-g9c0d40aba built on MoarVM version 2017.07-18-ga052a333
implementing Perl 6.c.
```

**Comment by evanmiller** [comment]
I've updated everything and appear to have newer versions of both Rakudo and MoarVM:

```
This is Rakudo version 2017.07-83-g9658dd98c built on MoarVM version 2017.07-243-g6941cada
implementing Perl 6.c.
```

I.e. Rakudo build 83 and MoarVM build 243 (compared to your 71 and 18). MoarVM is pointing to the "master" branch. NQP is behind master, but I can try updating that too.

**Comment by tony-o** [comment]
Hmm..i'll update and test again.  Are you in IRC?

**Comment by tony-o** [comment]
With fresh p6 I'm still passing test 07 - what OS are you on?

```This is Rakudo version 2017.07-83-g9658dd98c built on MoarVM version 2017.07-244-g86b70a27
implementing Perl 6.c.```

**Comment by evanmiller** [comment]
Updated NQP, still no luck. Running Mac OS X 10.12.6.

evanm on IRC; I will log on in about an hour.

**Comment by evanmiller** [comment]
Fixed in https://github.com/perl6/perl6-http-server-async/commit/75c4441a24db9d1a76330a31ab2209c586bef10f
